don't use EnumBuilder as it fails to emit the underlying value__ field of enums as public which causes integration problems with c# (error CS0656: The compiler required member `EnumFromBoo.value__' could not be found or is inaccessible) - unfortunately this fix causes a regression (BOO-1078) but it's better to be able to interoperate with c# at this point while I try to find a better solution (specially because BOO-1078 can be worked around by defining the enums and attributes in separate assemblies)